### ISSUE TITLE
Custom Function query for sorting in solr is giving error(ValueSource class was implemented for the sorting))

### ISSUE THREAD

**Issue by anagaram** [treygrainger/solr-in-action#2]
Hi,

I have a custom function query and also made solr recognize it by adding the class name in solr.xml. Even though solr loads the class it does not execute it and gives an error saying 

"solr cannot determine sort order".

Could you help me out in knowing if the error was caused in the custom function query as the error does not point to the location of the class named after custom function query.(OR) did I do any wrong in creating a jar for the custom query function as I could have misunderstood how the jar should be so that solr can execute it. I created the jar without including the depedencies as, if I include the depedencies I get Manifest error. I used maven in writing the implementation for ValuseSource class and ValueSourceParser.

The error that appears in solr is as follows::
```
org.apache.solr.common.SolrException: Can't determine a Sort Order (asc or desc) in sort spec 'CustomRanking(feild1,feild2,someString) desc', pos=58
	at org.apache.solr.search.QueryParsing.parseSortSpec(QueryParsing.java:340)
	at org.apache.solr.search.QParser.getSort(QParser.java:247)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:175)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:197)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:1967)
	at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:777)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:418)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:368)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:942)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1004)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
	at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)

```
Regards,
Aditya Reddy.

**Comment by anagaram** [comment]
The error was due to the last argument of the customfunction, which is of type string and if the last string contains a whitespace then it gives that error when used along with the velocity template.
