### ISSUE TITLE
Error Ch.14 

### ISSUE THREAD

**Issue by casertap** [treygrainger/solr-in-action#6]
Hi, very good book, thank you very much.
I have a bug when I try to run the example on chapter 14.
I did not get any trouble until then.

```
root@26d2788a65e0:/code# cd $SOLR_INSTALL/example/
root@26d2788a65e0:/opt/solr/example# cp -r $SOLR_IN_ACTION/example-docs/ch14/cores/* solr/
root@26d2788a65e0:/opt/solr/example# cp $SOLR_IN_ACTION/solr-in-action.jar solr/lib/
root@26d2788a65e0:/opt/solr/example# java -jar start.jar
0    [main] INFO  org.eclipse.jetty.server.Server  – jetty-8.1.10.v20130312
32   [main] INFO  org.eclipse.jetty.deploy.providers.ScanningAppProvider  – Deployment monitor /opt/solr-4.10.4/example/contexts at interval 0
36   [main] INFO  org.eclipse.jetty.deploy.DeploymentManager  – Deployable added: /opt/solr-4.10.4/example/contexts/solr-jetty-context.xml
1020 [main] INFO  org.eclipse.jetty.webapp.StandardDescriptorProcessor  – NO JSP Support for /solr, did not find org.apache.jasper.servlet.JspServlet
1100 [main] INFO  org.apache.solr.servlet.SolrDispatchFilter  – SolrDispatchFilter.init()
1139 [main] INFO  org.apache.solr.core.SolrResourceLoader  – JNDI not configured for solr (NoInitialContextEx)
1140 [main] INFO  org.apache.solr.core.SolrResourceLoader  – solr home defaulted to 'solr/' (could not find system property or JNDI)
1141 [main] INFO  org.apache.solr.core.SolrResourceLoader  – new SolrResourceLoader for directory: 'solr/'
1142 [main] INFO  org.apache.solr.core.SolrResourceLoader  – Adding 'file:/opt/solr-4.10.4/example/solr/lib/.DS_Store' to classloader
1143 [main] INFO  org.apache.solr.core.SolrResourceLoader  – Adding 'file:/opt/solr-4.10.4/example/solr/lib/solr-in-action.jar' to classloader
1146 [main] INFO  org.apache.solr.core.SolrResourceLoader  – Adding 'file:/opt/solr-4.10.4/example/solr/lib/.emptydir' to classloader
1232 [main] ERROR org.apache.solr.servlet.SolrDispatchFilter  – Could not start Solr. Check solr/home property and the logs
1257 [main] ERROR org.apache.solr.core.SolrCore  – null:java.lang.IllegalAccessError: class org.apache.lucene.codecs.diskdv.DiskDocValuesProducer cannot access its superclass org.apache.lucene.codecs.lucene45.Lucene45DocValuesProducer
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
````
The problem comes from the compiled solr-in-action.jar that is placed under solr/lib and failed the startup of solr.
I tried removing all the newly added cores of the ch14 and the problem persist.
Only when I remove the solr/lib/solr-in-action.jar that the error disappear.

The pom.xml is configured to be self contained using the maven-assembly-plugin but it seems to have a problem.
Can you please help me debug this?

**Comment by casertap** [comment]
If I copy the solr-in-action.jar in ```exemple/solr/lib/``` I get this error.
If I add 
````
  <lib dir="../../../contrib/solrinaction/" regex=".*\.jar" />
`````
in solrconfig.xml and I copy the solr-in-action.jar in ```contrib/solrinaction```` the log does not show anything abnormal but the core does not start.

Please help.

**Comment by casertap** [comment]
Ch15. I decided to move the library in ```exemple/solr/news/lib/solr-in-action.jar```
This lib get loaded at the very beginning of the startup of the core. 
From this moment, the core goes not show any more log so loading the solr-in-action.jar lib make the core freeze.
````
1667 [coreLoadExecutor-5-thread-2] INFO  org.apache.solr.core.SolrResourceLoader  – new SolrResourceLoader for directory: '/opt/solr-4.10.4/example/solr/news/'
1669 [coreLoadExecutor-5-thread-2] INFO  org.apache.solr.core.SolrResourceLoader  – Adding 'file:/opt/solr-4.10.4/example/solr/news/lib/solr-in-action.jar' to classloader

.... lot of log showing the startup of others core but not the news core
````

**Comment by casertap** [comment]
I think I found a way to make it work by removing the link to ```../../../contrib/solrinaction/```and copying the lib SNAPSHOT.jar on ```$SOLR_INSTALL/example/solr/news/lib/```

```cp $SOLR_IN_ACTION/target/solr-in-action-1.0_solr-4.7.0-SNAPSHOT.jar $SOLR_INSTALL/example/solr/news/lib/``` worked

**Comment by priyadb** [comment]
@casertap I ran into the same issue and was able to quickly resolve it by using the snapshot jar file. Thank you!
